name: Mobile Dev Action iOS

defaults:
  run:
    working-directory: apps/expo
on:
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Generate build
        run: yarn maestro:build:development:ios

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ${{ env.APP_DIR_PATH }}
          env: |
            PLATFORM=ios
